---
- include: ../playbooks/cluster.yml
  vars:
    CLUSTER_NAME: edxapp
    CLUSTER_INSTANCE_TYPE: t2.xlarge
    CLUSTER_ELBS:
      - name: "{{ COMMON_DEPLOYMENT }}-elb-{{ CLUSTER_NAME }}"
        health_check:
          ping_protocol: http
          ping_port: 80
          response_timeout: 5  # seconds
          interval: 30  # seconds
          unhealthy_threshold: 2  # attempts
          healthy_threshold: 10  # attempts
        listeners:
          - protocol: http
            load_balancer_port: 80
            instance_port: 80
          - protocol: https
            load_balancer_port: 443
            instance_port: 80
            instance_protocol: htp
            ssl_certificate_id: "{{ DEPLOYMENT_SSL_CERTIFICATE_ID }}"
        scheme: internet-facing
        subnets: "{{ CLUSTER_ELB_SUBNETS }}"
        groups: "{{ cluster_security_group.group_id }}"
- name: Setup edxapp
  hosts: cluster_group_launched
  gather_facts: True
  become: true
  vars:
    CLUSTER_NAME: edxapp
    COMMON_HOSTNAME: "{{ COMMON_DEPLOYMENT }}-box-{{ CLUSTER_NAME }}-{{ CLUSTER_NUMBER }}"
    nginx_sites:
     - lms
     - cms
     - verify
    nginx_default_sites:
     - lms
    NGINX_REDIRECT_TO_HTTPS: true
  vars_files:
    - "{{ COMMON_DEPLOYMENT_DIR }}/common.yaml"
    - "{{ COMMON_DEPLOYMENT_DIR }}/edxapp-common.yaml"
    - "{{ COMMON_DEPLOYMENT_DIR }}/edxapp.yml"
    - "{{ COMMON_DEPLOYMENT_DIR }}/embargo.yaml"
  roles:
    - role: nginx
      tags: nginx
    - role: edxapp
      tags: edxapp
