- hosts: ~tag_Name_{{ machine }}_{{ env }}
  sudo: True
  gather_facts: True
  vars_files:
    - "{{ COMMON_DEPLOYMENT_DIR }}/data-api.yml"
  vars:
    ENABLE_DATADOG: False
    ENABLE_SPLUNKFORWARDER: False
    COMMON_ENABLE_DATADOG: False
    COMMON_ENABLE_SPLUNKFORWARDER: False
    COMMON_TAG_EC2_INSTANCE: False
  roles:
    - role: nginx
      nginx_sites:
        - analytics_api
    - role: analytics_api
      tags: analytics_api
