#!/usr/bin/env ansible-playbook
---
- include: ../playbooks/cluster.yml
  vars:
    CLUSTER_ASSIGN_PUBLIC_IP: yes
    CLUSTER_NAME: jump
    CLUSTER_NETWORK: public
  when: redeploy | default(False) | bool
- name: 'Setup jumpbox'
  hosts: "tag_Cluster_jump:&tag_todo_deploy:&tag_Deployment_{{ COMMON_DEPLOYMENT }}:&tag_Number_{{ CLUSTER_NUMBER }}"
  gather_facts: True
  become: true
  vars:
    CLUSTER_NAME: jump
    CLUSTER_NETWORK: public
  vars_files:
    - "{{ COMMON_DEPLOYMENT_DIR }}/common.yaml"
  roles:
    - role: common
      tags: common
