#!/usr/bin/env ansible-playbook
---
# TODO: configure subnet to use non-default/public route table
- include: ../playbooks/cluster.yml
  vars:
    ansible_ssh_common_args: ''
    CLUSTER_ASSIGN_PUBLIC_IP: yes
    CLUSTER_NAME: jump
    CLUSTER_SECURITY_GROUPS:
      - "{{ CLUSTER_SECURITY_GROUP }}"
- name: 'Setup jumpbox'
  hosts: cluster_group_launched
  gather_facts: True
  become: true
  vars:
    ansible_ssh_common_args: ''
    CLUSTER_NAME: jump
    COMMON_HOSTNAME: "{{ COMMON_DEPLOYMENT }}-box-{{ CLUSTER_NAME }}-{{ CLUSTER_NUMBER }}"
  vars_files:
    - "{{ COMMON_DEPLOYMENT_DIR }}/common.yaml"
  roles:
    - role: common
      tags: common
