#!/usr/bin/env ansible-playbook
---
- include: ../playbooks/cluster.yml
  vars:
    CLUSTER_NAME: notifier
    CLUSTER_SECURITY_GROUPS:
      - "{{ CLUSTER_SECURITY_GROUP }}"
- name: Create the notifier
  hosts: cluster_group_launched
  gather_facts: True
  become: True
  vars:
    CLUSTER_NAME: notifier
    COMMON_HOSTNAME: "notifier{{ CLUSTER_NUMBER }}.{{ COMMON_DEPLOYMENT }}.vpc"
  vars_files:
    - "{{ COMMON_DEPLOYMENT_DIR }}/{{ CLUSTER_NAME }}.yml"
    - "{{ COMMON_DEPLOYMENT_DIR }}/common.yaml"
  roles:
    - role: notifier
      tags: notifier
