#!/usr/bin/env ansible-playbook
---
- include: ../playbooks/cluster.yml
  vars:
    CLUSTER_NAME: rabbitmq
    CLUSTER_ELBS:
      - name: "{{ COMMON_DEPLOYMENT }}-elb-{{ CLUSTER_NAME }}"
        health_check:
          ping_protocol: tcp
          ping_port: 5672
          response_timeout: 5  # seconds
          interval: 30  # seconds
          unhealthy_threshold: 2  # attempts
          healthy_threshold: 10  # attempts
        listeners:
          - protocol: tcp
            load_balancer_port: 5672
            instance_port: 5672
          - protocol: tcp
            load_balancer_port: 6163
            instance_port: 6163
        scheme: internal
        subnets: "{{ CLUSTER_ELB_SUBNETS }}"
        groups: "{{ cluster_security_group.group_id }}"
      - name: "{{ COMMON_DEPLOYMENT }}-elb-{{ CLUSTER_NAME }}-www"
        health_check:
          ping_protocol: http
          ping_path: '/'
          ping_port: 15672
          response_timeout: 5  # seconds
          interval: 30  # seconds
          unhealthy_threshold: 2  # attempts
          healthy_threshold: 10  # attempts
        listeners:
          - protocol: https
            load_balancer_port: 443
            instance_port: 15672
            ssl_certificate_id: "{{ DEPLOYMENT_SSL_CERTIFICATE_ID }}"
        scheme: internet-facing
        subnets: "{{ CLUSTER_ELB_SUBNETS }}"
        # TODO: actually create this too!
        groups: "{{ COMMON_DEPLOYMENT }}-elb-{{ CLUSTER_NAME }}-www"
- name: Setup rabbit
  hosts: cluster_group_launched
  gather_facts: True
  become: true
  vars:
    CLUSTER_NAME: rabbitmq
    COMMON_HOSTNAME: "{{ COMMON_DEPLOYMENT }}-box-{{ CLUSTER_NAME }}-{{ CLUSTER_NUMBER }}"
  vars_files:
    - "{{ COMMON_DEPLOYMENT_DIR }}/common.yaml"
    - "{{ COMMON_DEPLOYMENT_DIR }}/{{ CLUSTER_NAME }}.yml"
  roles:
    - supervisor
    - rabbitmq
