#!/usr/bin/env ansible-playbook
---
- include: ../playbooks/cluster.yml
  vars:
    CLUSTER_NAME: xqueue
- name: Setup XQueue
  hosts: cluster_group_launched
  gather_facts: True
  become: true
  vars:
    CLUSTER_NAME: xqueue
    COMMON_HOSTNAME: "{{ COMMON_DEPLOYMENT }}-box-{{ CLUSTER_NAME }}-{{ CLUSTER_NUMBER }}"
  vars_files:
    - "{{ COMMON_DEPLOYMENT_DIR }}/common.yaml"
    - "{{ COMMON_DEPLOYMENT_DIR }}/edxapp-common.yaml"
    - "{{ COMMON_DEPLOYMENT_DIR }}/edxapp.yml"
    - "{{ COMMON_DEPLOYMENT_DIR }}/xqueue.yml"
  roles:
    - role: nginx
      tags: nginx
      nginx_sites:
        - xqueue
    - role: xqueue
      tags: xqueue
