---
CLUSTER_AMI: 'ami-09d2fb69'
CLUSTER_ASSIGN_PUBLIC_IP: no
CLUSTER_EBS_SIZE: 16
CLUSTER_ELB_GROUPS: "{{ CLUSTER_SECURITY_GROUPS }}"
CLUSTER_SECURITY_GROUP: "{{ COMMON_DEPLOYMENT }}-group-{{ CLUSTER_NAME }}"
CLUSTER_SECURITY_GROUP_DESCRIPTION: "Secure {{ COMMON_DEPLOYMENT }}-{{ CLUSTER_NAME }} clusters"
CLUSTER_SUBNET_AZ: "{{ region }}a"
CLUSTER_SUBNET_TAGS:
      Name: "{{ COMMON_DEPLOYMENT }}-subnet-{{ CLUSTER_NAME }}-{{ CLUSTER_NUMBER }}"
      Deployment: "{{ COMMON_DEPLOYMENT }}"
      Cluster: "{{ CLUSTER_NAME }}"
      Number: "{{ CLUSTER_NUMBER }}"
CLUSTER_ELB_SUBNETS:
  - "{{ CLUSTER_SUBNET_ID }}"
CLUSTER_ELBS: []
CLUSTER_INSTANCE_TYPE: t2.micro
CLUSTER_KEY: "{{ COMMON_DEPLOYMENT }}-key-deploy"
CLUSTER_NAME: 'TODO'
CLUSTER_NUMBER: 1
CLUSTER_REGION: 'us-west-1'
CLUSTER_SECURITY_GROUPS:
  - "{{ CLUSTER_SECURITY_GROUP }}"
CLUSTER_SUBNET_ID: subnet-XXXXXX

CLUSTER_NETWORK: private
